filesystem:
  path: ./test
  files_permission: 770
  directories_permission: 770
git:
  repo: "git@github.com:Ferlab-Ste-Justine/ferlease-playground.git"
  ref: main
  path: qa
  auth:
    ssh_key: "~/.ssh/id_rsa"
    known_key: "known_host"
  accepted_signatures: ""
grpc_notifications:
  - endpoint: "127.0.0.10:8080"
    max_chunk_size: 1048576
    connection_timeout: "30s"
    request_timeout: "30s"
    retry_interval: "30s"
    retries: 10
notification_command:
  - echo
  - "updated!"
notification_command_retries: 5
log_level: info